name: mrtg
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python==3.9
  - pip
  - pytorch
  - ipykernel
  - numpy==1.26.4
  - matplotlib
  - scikit-learn
  - h5py
  - pip:
      - tqdm
      - torch_topological
